### ISSUE TITLE
Client creation with `DefaultAzureCredential` raises PyCharm typing warning

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-python#25175]
Per https://github.com/Azure/azure-sdk-for-python/pull/25144, opened by @soer7022. As shown in the screenshot below, PyCharm sometimes raises a flag for incorrect typing when creating a Key Vault `SecretClient` with a `DefaultAzureCredential`.

![image](https://user-images.githubusercontent.com/39780829/178386865-3aaeda88-c5ed-4f33-a737-64de36000e4a.png)

`DefaultAzureCredential` is an implementation of the [`TokenCredential` protocol](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#tokencredential-protocol), so the typing is correct (and the type hint on the KV client should be kept as-is for generality). However, we should find a way to indicate this protocol implementation in a way that prevents false flags like this.

Running `isinstance(DefaultAzureCredential, TokenCredential)` currently raises an error because `TokenCredential` isn't decorated with [`@runtime_checkable`](https://docs.python.org/3/library/typing.html#typing.runtime_checkable), but adding this decorator and running the statement returns `True` (`mypy` doesn't raise an error with or without the decorator). This may be the fix we need, but there may be more to do here -- refer to [PEP 544](https://peps.python.org/pep-0544/) for more information.

**Comment by soer7022** [comment]
The screenshot is from my system, I'm running the following:
- PyCharm 2022.1.3 (Professional Edition)
- Python 3.10.1
- azure-identity 1.10.0
- azure-keyvault-secrets 4.4.0

**Comment by mccoyp** [comment]
Hi @soer7022! When you get a chance, would you be willing to try applying the changes from https://github.com/Azure/azure-sdk-for-python/pull/25187 to your local `azure-core` package to see if that resolves the issue? I haven't been able to reproduce the warning, possibly because I'm not using PyCharm's professional edition.

**Comment by soer7022** [comment]
Unfortunately, the changes in the PR did not fix it. And neither did the ones described in the description...
Did you try updating your PyCharm to a 2022 version? 😄

**Comment by mccoyp** [comment]
Hmmm... I wasn't able to keep looking into this today, but I'll keep trying to repro and provide an update as soon as possible. I updated my PyCharm yesterday, but I'll see if there are updates I'm missing -- thank you for your patience!

**Comment by mccoyp** [comment]
Hi again @soer7022 -- sorry about the delayed response on this, but I was able to reproduce the warning after updating to Community Edition 2022.1.3 🙂 I'll provide an update again as soon as possible.

**Comment by mccoyp** [comment]
A PR is now up to fix this: https://github.com/Azure/azure-sdk-for-python/pull/25788

**Comment by xiangyan99** [comment]
@mccoyp I guess it is already fixed?

**Comment by mccoyp** [comment]
@xiangyan99 it's not -- I actually need to sync with Laurent about this.

https://github.com/Azure/azure-sdk-for-python/pull/25187 made `isinstance` checks with the protocols possible, but that doesn't fix the PyCharm typing issue. We need either https://github.com/Azure/azure-sdk-for-python/pull/25788 or a change to our `get_token` signatures to fix this issue (the description of https://github.com/Azure/azure-sdk-for-python/pull/25788 explains the reasoning).

**Comment by jlipmanDig** [comment]
Hi, any update on this issue? we're facing something similar which forces us to silence the type-checking for azure credentials

**Comment by mccoyp** [comment]
Hi @jlipmanDig, I'm working on this issue now and we'll hopefully have a fix included in the next `azure-identity` release after this week's. A PR should be up later this week -- apologies for the delay.

**Comment by jlipmanDig** [comment]
Thanks @mccoyp! Looking forward to it 😊
