### ISSUE TITLE
Cannot import name 'AccessTokenInfo' from 'azure.core.credentials'

### ISSUE THREAD

**Issue by miladh** [Azure/azure-sdk-for-python#37491]
- **Package Name**: az-ai-ml
- **Package Version**:  1.19.0
- **Operating System**: Linux
- **Python Version**:  3.11

**Describe the bug**
> [!NOTE] 
> Apologies if this issue should have been created in a different repository. Please let me know if I should create this ticket elsewhere.

In [this PR](https://github.com/Azure/azure-sdk-for-python/pull/36882), the minimum version of azure-core was updated to include the new `SupportTokenInfo` protocol and `AccessTokenInfo` class. However, when attempting to install the Azure ML extension using:

```
az extension add --name ml
``` 

the following error occurs:

```
cannot import name 'AccessTokenInfo' from 'azure.core.credentials'
```

As this issue is currently disrupting our CI pipelines, we would be grateful for any guidance you can provide to help us address it promptly.

### Possible Cause

This issue seems to arise because the Azure ML extension installs `azure_identity-1.18.0`, which relies on `AccessTokenInfo` from `azure.core.credentials`. However,  `azure-cli` version `2.64.0` still uses an older version of azure-core (`1.28.0`), and hence the error above is thrown.

For reference, here’s the [azure-cli requirements file](https://github.com/Azure/azure-cli/blob/azure-cli-2.64.0/src/azure-cli/requirements.py3.Linux.txt#L11).

**To Reproduce**
1. Install az cli
2. Run `az extension add --name ml`

**Comment by levu74** [comment]
Yes, same for me. It's now a blocker for my CI pipelines.

**Comment by rikwatson** [comment]
This is no blocking all my ML pipelines

**Comment by MetelStairs** [comment]
This is also blocking our pipelines also

**Comment by dionhaefner** [comment]
Thanks for the pointer to `azure-identity` @miladh – this works for me as a workaround on CI:

```bash
$ az extension add --upgrade --name ml -y
$ sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1
```

**Comment by rikwatson** [comment]
Also a blocker for me (muliple training pipelines)

**Comment by pimonteiro** [comment]
> azure-cli

This workaround did work on our case.

**Comment by pimonteiro** [comment]
> Thanks for the pointer to `azure-identity` @miladh – this works for me as a workaround on CI:
> 
> ```shell
> $ az extension add --upgrade --name ml -y
> $ sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1
> ```
> 
> (use at your own risk)

This workaround did work on our case.

**Comment by pvaneck** [comment]
Appears that there is some intermingling of dependencies.

Looking at where CLI extension dependencies are installed for me, (`~/.azure/cliextensions/ml`), I do see that there are compatible versions of `azure-core` and `azure-identity` installed. However, the versions of these packages installed in the `azure-cli` Python virtual environment (e.g. `/opt/az/lib/python3.11/site-packages/`) seem to take precedence at runtime causing incompatibilities. 

I mentioned this in the linked azure-cli [issue](https://github.com/Azure/azure-cli/issues/29940), but I think something may need updating in the dependency resolution logic when installing an extension. Ideally, azure-cli extension Python requirements should remain compatible with the base azure-cli requirements when the extension is installed (i.e. azure-identity 1.17.1 should automatically have been installed with the ML extension).

I believe the **workaround**, as mentioned above, is to install an older version of azure-identity in whatever virtual environment azure-cli is using. 

Example workarounds:

**Linux**:
```bash
sudo /opt/az/bin/python3 -m pip install azure-identity==1.17.1
```

**Windows** (in elevated/administrator terminal):
```bash
C:\"Program Files (x86)"\"Microsoft SDKs"\Azure\CLI2\python.exe -m pip install azure-identity==1.17.1
```

Not sure about Mac, but probably just need to run the python executable somewhere in `/opt/homebrew/Cellar/azure-cli/<version>/libexec/` ?

I think you can glean the location of the environment your azure-cli is using based on the error message:

`cannot import name 'AccessTokenInfo' from 'azure.core.credentials' (/opt/az/lib/python3.11/site-packages/azure/core/credentials.py)` -> Need to use python executable somewhere in `/opt/az`

**Comment by levu74** [comment]
@pvaneck for Linux, the workaround works.  On my Windows machine, I ran the command (64-bit version), but it doesn't work.

**Comment by toby-coleman** [comment]
Same issue here - stopping all of our CI pipelines.

**Comment by adtcode216** [comment]
As a temporary solution, you can add the following to your requirements.txt for a quick CI pipelines fix:

`azure-identity==1.17.1`

**Comment by steflommen** [comment]
> @pvaneck for Linux, the workaround works. On my Windows machine, I ran the command (64-bit version), but it doesn't work.

For our azure pipelines the following pipeline works
`      C:\"Program Files"\"Microsoft SDKs"\Azure\CLI2\python.exe -m pip install azure-identity==1.17.1
`

**Comment by PratibhaShrivastav18** [comment]
This issue has been resolved. Please retry.
`az extension add --name ml --version 2.30.0`

**Comment by ezpzzz19** [comment]
please correct me if I am misunderstanding but this solution assumes that we are using / installed the azure-cli package. In our case we are not. 
Will there be a fix directly on the newest version of azure-identity to solve the problem ? We would ideally want to stay up to date with the newest version of azure-identity

**Comment by pvaneck** [comment]
@ezpzzz19 The latest version of `azure-identity` already requires the version of `azure-core` which contains the necessary imports. You shouldn't be encountering this issue if you are installing normally through `pip` as the dependency resolution will ensure you have compatible versions of `azure-core` and `azure-identity`.

If you are seeing this issue outside of the context of Azure CLI or the Azure CLI ML extension, then please open another issue.

**Comment by JSchoeck** [comment]
The mentioned issue https://github.com/Azure/azure-sdk-for-python/issues/37790 has two fixes that work for me:
1. Pin azure-identity to 1.17.1 and azure-core to <1.31.0 or
2. Disable Application Insights for the web app:
    Application Insights [Preview]
    Collect application monitoring data using Application Insights
    --> Disable

**Comment by achauhan-scc** [comment]
@jeremydvoss  / @miladh  - Are we still facing the similar issue with latest version of CLI extension 2.34.0?

**Comment by miladh** [comment]
> [@jeremydvoss](https://github.com/jeremydvoss) / [@miladh](https://github.com/miladh) - Are we still facing the similar issue with latest version of CLI extension 2.34.0?

Using version 2.33.1 currently and no longer facing the issue.

**Comment by jeremydvoss** [comment]
> [@jeremydvoss](https://github.com/jeremydvoss) / [@miladh](https://github.com/miladh) - Are we still facing the similar issue with latest version of CLI extension 2.34.0?

This is unrelated to any CLI extension.

**Comment by jeremydvoss** [comment]
For those getting the same error on App Service despite specifying the right version of azure-core==1.32.0, [that issue](https://github.com/Azure/azure-sdk-for-python/issues/37790?reload=1) has been fixed.

Since the separate issue of az-ai-ml appears to be solved with version 2.33.1. I recommend closing this issue.
