### ISSUE TITLE
Consuming duplicate lag events intermittently while using in-memory checkpoint

### ISSUE THREAD

**Issue by gjjtip0926** [Azure/azure-sdk-for-python#41024]
- **Package Name**: azure-eventhub
- **Package Version**: 5.7.0
- **Operating System**: linux
- **Python Version**: 3.6

**Describe the bug**
While using in-memory checkpoint to manage offset, the code consumes duplicate events data intermittently after restarting and running 2-3 hours.

**To Reproduce**
1. Restart the application and start reading events since latest timestamp
2. Monitor 2-3 hours and log the event data including offset, enqueued time, seq number
3. Application starts reading old data with old offset after running a few hours, without any exception

**Expected behavior**
Expect the in-memory checkpoint to work and manage offset correctly, to prevent consuming any old data.

**Screenshots**
column: log timestamp(utc+8), offset, seq number, event enqueued time(utc)
![Image](https://github.com/user-attachments/assets/70b3534f-3922-454e-bc3b-0e7caf1203ea)

for example, I restarted application by around 3:31 AM, it running well until around 6:26 AM.  It started reading a snippet of lag data with same offset range endlessly, and never recovered unless restart the application again.

**Additional context**

**sample code:**
   ```
 async def main(auth):
       eventhub_connect = "Endpoint=***"
       eventhub_name = "***"
       client = EventHubConsumerClient.from_connection_string(
        eventhub_connect, consumer_group="***", eventhub_name=eventhub_name
    )

    async with client:
    await client.receive_batch(
        on_event_batch=on_event,
        starting_position=datetime.datetime.now().replace(second=0, microsecond=0), max_wait_time=10, max_batch_size=1000,
    )

    async def on_event(partition_context, event_batch):
        for event in event_batch:
            data = json.loads(event.body_as_str(encoding="UTF-8"))
            print(data)
            await partition_context.update_checkpoint()
```

**Ask:**
Same code is working fine in other applications with same in-memory scenario.
Is it related to "not well managed" offset due to in-memory update_checkpoint() method? Any possible reason about this symptoms? 
Any suggestion to narrow down the in-memory update_checkpoint() details like log the details about every offset commit action or fetch offset request?

**Comment by swathipil** [comment]
Hi @gjjtip0926 - We fixed an issue related to reprocessing old events in [v5.11.4](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/CHANGELOG.md#bugs-fixed-8).

In addition to the suggestions from the comment above, I would suggest that you upgrade to the latest azure-eventhub version, 5.15.0, in order to get all the latest bug fixes and Python version 3.8, as that is the minimum supported version. Thanks!

**Comment by gjjtip0926** [comment]
@swathipil Thanks for your reply. May you kindly confirm if the bug fix is related to Blob checkpoint store? 
I am experiencing the issue on in-memory checkpoint store basically.

**Comment by kashifkhan** [comment]
@gjjtip0926 This particular fix was made at the SDK level, so it would benefit blob, in-memory etc. As Swathi mentioned you also want to make sure that the async event loop is not blocked as it can also lead to such issues, so best would be to use `asyncio.to_thread` to avoid that.

**Comment by gjjtip0926** [comment]
The issue still exists after upgrading the SDK to latest version 5.15.0.

Would you please share more detailed way like how to use use asyncio.to_thread to avoid async event loop blocking.

**Comment by kashifkhan** [comment]
@gjjtip0926 one of the ways would be to look for sync calls that can block the event loop. In the example shared above that would be this section of code here 

```python
data = json.loads(event.body_as_str(encoding="UTF-8"))
```

it would be changed to 
```python
data = await asyncio.to_thread(json.loads, event.body_as_str(encoding="UTF-8"))
```
