### ISSUE TITLE
Unable to read topic subscription ( python3.5 )

### ISSUE THREAD

**Issue by colin-streicher** [Azure/azure-sdk-for-python#956]
When running this:
I've left out the initialization because it contains sensitive information, but I've no reason to believe that that is not working. The subscription shows up in the portal, but reading messages always gives me the following error. 
My python version is 3.5, I'm on a Mac, but I don't think that is relevant. 

```
bus_service.create_subscription('test01','AllMessages')
msg = bus_service.receive_subscription_message('test01', 'AllMessages', peek_lock=True)
print(msg)
```

I end up with this:

```
Traceback (most recent call last):
  File "mb.py", line 15, in <module>
    msg = bus_service.receive_subscription_message('test01', 'AllMessages', peek_lock=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/azure/servicebus/servicebusservice.py", line 972, in receive_subscription_message
    timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/azure/servicebus/servicebusservice.py", line 700, in peek_lock_subscription_message
    return _create_message(response, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/azure/servicebus/_serialization.py", line 102, in _create_message
    elif str(int(float(value))) == value:
ValueError: could not convert string to float: 'max-age=31536000'
```

**Comment by lmazuel** [comment]
Hi @colin-streicher 
This is a known issue of version <=0.20.1 (see [ChangeLog](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicebus/HISTORY.rst)). Please update your `azure-servicebus` package to at least 0.20.2 (latest one is 0.21.0).

**Comment by colin-streicher** [comment]
Great, thanks!
It is likely worth pointing out that I just installed this today through 'pip3.5 install azure', since it looks like this bug was fixed last june, it seems like it should have made it in by now. Anyways, I'll update from git, thanks again.

**Comment by lmazuel** [comment]
I totally understand how you find yourself in this situation... I try to explain for you customers that the current `azure` meta-package stable 1.0.3 is deprecated and should not be used, but it's far from obvious and I totally get it:
http://azure-sdk-for-python.readthedocs.io/en/latest/installation.html

The ARM part of `azure` 1.0.3 is deprecated, but we still not have the stable part of ARM that will be `azure` 2.0.0. However, each day I release that it's not fair for Legacy users and ServiceBus users (i.e. not ARM) because there is bug fixes for their packages.

Thank you for your bug report, it enhances my thinking on this.
